# Generated by Django 4.1 on 2022-09-10 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_watchlist_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Platform',
            new_name='StreamPlatform',
        ),
    ]
