# Generated by Django 4.1 on 2022-09-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(null=True, upload_to='xmedia'),
        ),
    ]
